### ISSUE TITLE
Prevent player from joining / starting game if a players bot does not exist.

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-api#106]
Scenario: 
- Player creates a wombat
- Player joins game
- Player removes wombat code
- Game starts

Expected: 
- API gracefully handles missing / malformed player code
- API notifies client / individual player of the errors

**Comment by morganedmonds** [comment]
This issue needs additional discussion. We could verify that wombats have an associated repo, but users could remove/move their repo in Github. We need to determine a way to handle this situation, or alert the user.

**Comment by morganedmonds** [comment]
Moving to blocked until there is a conversation around how to handle this.

**Comment by morganedmonds** [comment]
If the user tries to join a game, we check to see if you're already joined, if you're a valid player, if the Wombat exists, and if the Wombat belongs to current user. Failing a check sends an error to the client. 

Moving to building.

**Comment by morganedmonds** [comment]
This looks good per the comments above on expected behavior. Moving to complete.
