### ISSUE TITLE
Games - Search

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-api#117]
This ticket is for faceted search endpoint for games.

Shameless plug: http://willowtreeapps.com/blog/text-searching-with-mongodb/

![image](https://cloud.githubusercontent.com/assets/4649439/18225146/1a6f5ecc-71ba-11e6-81ee-e2a6b7e6bb67.png)

**Comment by morganedmonds** [comment]
This can be V2, but we should prioritize high in the backlog.

**Comment by morganedmonds** [comment]
Duplicate
