### ISSUE TITLE
Gameplay - Frame Processing - Push Changes to Client

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-api#152]
After we have evaluated user choices ( #101 ) and resolved any conflicts ( #151 ), we should push changes to both the database and client in order to update the frame.

**Comment by oconn** [comment]
@morganedmonds could we break this up into two tickets? I'll do the work for pushing changes to the client in this one via web sockets, but we should create a new one for updating the db.

**Comment by morganedmonds** [comment]
@oconn I've updated this ticket and created #186 for updating the database.
