### ISSUE TITLE
Games - Get Ongoing Games

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-api#156]
Get a list of all ongoing games. 

This depends on #114 .

**Comment by emilyseibert** [comment]
Decided on polling for updates ~1min if user is stagnant on screen. As the page refreshes or is navigated to, insure that panel repolls for games.

**Comment by emilyseibert** [comment]
@morganedmonds  this should be for wombats web client i believe

**Comment by morganedmonds** [comment]
@emilyseibert I'm not able to move the issue to the correct repo, but I could create a new one for you on the client if you'd like.

**Comment by emilyseibert** [comment]
No biggie. just lettin' ya know
