### ISSUE TITLE
Config - Arena/Game Config Updates

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-api#209]
Make the following elements configurable:

Wood Barrier HP
Steel Barrier HP
Zakano HP
Wombat HP
Collision Damage Amount
Food Bonus
Poison Damage
Score for Food Collection
Score for Accurate Shooting:
-- Hit Wombat
-- Hit Zakano
-- Hit Wood Barrier
-- Hit Steel Barrier
Shot Distance
Non-Transparent Types - what items cause fog of war (we may keep this as a constant)
Partial View Radius - default now is 3

**Comment by oconn** [comment]
Wood HP, Steel HP, Zakano HP,  and Wombat HP have been completed.

**Comment by morganedmonds** [comment]
This is now a duplicate, closing
