### ISSUE TITLE
[BUG] Arena is not updated for a given game after changes are made to the arena configuration

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-api#210]
Steps to Reproduce:
1. Create an arena, "Big Arena" with a 50x50 grid
2. Create a game using the "Big Arena" ID, called "Little Game"
3. Start game and observe that the arena has a 50x50 grid
5. Update "Big Arena" with a 10x10 grid
6. Start "Little Game"

Expected Results
A user may expect that the arena for the game would be updated to use a 10x10 grid

Actual Results 
Arena for that game retains the original configuration, with a 50x50 grid

This may not be a bug that we need to fix, but I'm logging for tracking.

**Comment by oconn** [comment]
This looks like it's working as intended and may have been addressed after the creation of this ticket. The follow is the code that supports clearing the arena. 

```clj
(defn clear-game-state []
  (re-frame/dispatch [:game/update-frame nil]) ;; Clears arena state on unmount
  (re-frame/dispatch [:game/clear-chat-messages])
  (re-frame/dispatch [:game/stats-update {}])
  (ws/send-message :leave-game {:game-id @game-id})
  (reset! game-id nil))
```
