### ISSUE TITLE
[BUG] I can join a game with max-players: 0

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-api#229]
Create a game with 0 max players
Attempt to join the game
No error thrown. Appears under games you've joined in the database (/api/v1/games filter by user id)

When attempting to join again, it throws an error that your user id is already in the game

I would expect that it'd be impossible to either create an game with 0 players or to join a game with 0 max players.

**Comment by morganedmonds** [comment]
Hopefully this is resolved in API ticket #215 to set min/max players. We should check back on this bug after that ticket is closed to see if we're still seeing any of this weird behavior.

**Comment by morganedmonds** [comment]
This has been resolved by preventing creation of a game with 0 players. Moving to closed.
