### ISSUE TITLE
Gameplay - Round reset arena on new rounds

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-api#242]
It is part of the AC for `:round` type games to re-seed users into the game on each round if they were eliminated in the previous round. All arena elements should also be re-seeded.

AC:

* For next round, generate new arena (same config)
* For next round, Wombats are restored to full health
* Scores accumulate and are shown in the status bar
* Spawn in new random spot at game start

**Comment by oconn** [comment]
Blocked by scheduling.

**Comment by morganedmonds** [comment]
This looks good based on the AC above. Only note is that the new arena is generated at the start of intermission, while Wombat health is restored at the end of intermission (start of next round). Should these be consistent? Moving to design review, we can consult with Jesse.
