### ISSUE TITLE
Set :round game type keyword to "High Score"

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-api#275]
The user should see "High Score" instead of ":round" on the game card for game type.

**Comment by morganedmonds** [comment]
@oconn @emilyseibert I'm seeing ":high-score" not "High Score" on the game card. Is that an API or client fix?

**Comment by emilyseibert** [comment]
client

**Comment by morganedmonds** [comment]
Fixed! Moving to closed.
