### ISSUE TITLE
Join Game - Display error if game starts while join modal is open

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-api#278]
Currently, the "Game Full" alert displays if a game starts while the join modal is open.

We should display a different alert for this scenario, based on Jesse's designs.

**Comment by emilyseibert** [comment]
this hsould be a web client ticket

**Comment by morganedmonds** [comment]
Happy path, this is working. 

There is an edge case where the user who attempts to join the game is the ONLY player to join the game. An error is not shown, and the user is navigated to the game screen. Then the game shows "ROUND 1 STARTS IN: 00:00", the player who joined is listed in the status bar, and the game has not started. 

I've created #250 to document that bug. Moving this issue to closed, since that is an edge case.
