### ISSUE TITLE
[Refactor] Update game-state & game

### ISSUE THREAD

**Issue by dehli** [willowtreeapps/wombats-api#305]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is for the API / Game Engine code base (not [Web Client](https://github.com/willowtreeapps/wombats-web-client), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## ISSUE DESCRIPTION

Currently `game-state` and `game` are incompatible with each other (b/c of formatting). The game's data is formatted differently in each of them, when game should be a subset of game-state.

**Comment by emilyseibert** [comment]
Please review tagged UI ticket (shown above) when testing for completion.

**Comment by morganedmonds** [comment]
This will be done with pair programming, which leads to the 2 day estimate. This includes relevant testing.

**Comment by oconn** [comment]
Acceptance Criteria: Game has identical behavior.

**Comment by morganedmonds** [comment]
This looks good to me (i.e. no change in game behavior). Closing.
