### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-api#322]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is for the API / Game Engine code base (not [Web Client](https://github.com/willowtreeapps/wombats-web-client), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST?

A feature request constitutes any feature not currently supported by the API / Game Engine that does not fall under a Game Play Request.

**- Describe the feature you would like to see.**
Track analytics events around how users interact with the game. 

**- Why you believe this would improve the quality of the Wombat's API / Game Engine.**
This would help provide evidence for which features to prioritize and understand how users are interacting with the game.

**- Provide details on expected behavior.**
We need to discuss which events to track. E.g. screen visits

**Comment by emilyseibert** [comment]
This is a front end ticket. Moving to web client.
