### ISSUE TITLE
Keys for Controlled Release

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-api#325]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is for the API / Game Engine code base (not [Web Client](https://github.com/willowtreeapps/wombats-web-client), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST

A feature request constitutes any feature not currently supported by the API / Game Engine that does not fall under a Game Play Request.

**- Describe the feature you would like to see.**
Create a key that would allow exclusive access to wombats.io

**- Why you believe this would improve the quality of the Wombat's API / Game Engine.**
We need a way to prevent carte blanche access to wombats.io. A way to do this would be to share keys with selected users that allows access. 

**- Provide details on expected behavior.**
Need to discuss what this will look like.

**Comment by emilyseibert** [comment]
What are keys
- unique
- user defined "uva hackathon" not guid
- contain metadata: a description of why the key has been created, event description
- configurable limit on # of users that can use the key
- expiration date

Flow
- On `/beta?beta_key=xyz`
- Authorize user through github and update them in db
- Check to see if user is in beta
- If not in beta, check to see if key is valid (valid if max uses haven't been reach, exp date has not been reach) 
- update key stats and update user to beta status
- redirect to client

**Comment by emilyseibert** [comment]
Will need to be able to accept a new key name and create in db

**Comment by oconn** [comment]
Acceptance Criteria: Users cannot log in without using an access key. If an access key is used they can log in as normal

**Comment by morganedmonds** [comment]
At a high-level, this appears to be working as expected. I'd love to test to make sure the limit works as expected, i.e. when 100 people have used the key, we get an error message (or something) that the key is invalid. @oconn what do you think?

**Comment by morganedmonds** [comment]
Tested and determined that I can log in with an expired access key. Still need to test capping number of users.

**Comment by morganedmonds** [comment]
Woooo this is fixed! Closing.
