### ISSUE TITLE
Application Error States

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-api#332]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is for the API / Game Engine code base (not [Web Client](https://github.com/willowtreeapps/wombats-web-client), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST?

A feature request constitutes any feature not currently supported by the API / Game Engine that does not fall under a Game Play Request.

- Describe the feature you would like to see.

Support for client error states

- Why you believe this would improve the quality of the Wombat's API / Game Engine.

PPl would know when something goes wrong

- Provide details on expected behavior.

Logging in
-key failed

Simulator
https://github.com/willowtreeapps/wombats-api/issues/331

**Comment by oconn** [comment]
Acceptance criteria: Messages are returned to the client to be displayed on access key failures.

**Comment by morganedmonds** [comment]
Seems to be working! Closing.
