### ISSUE TITLE
Multi-language Compiler Work Started Here

### ISSUE THREAD

**Issue by elibosley** [willowtreeapps/wombats-api#91]
At today's hackathon Eric and I managed to get this built out a little bit, so feel free to pull our code and use any of it!

https://github.com/erichahn/wombats-python

**Comment by oconn** [comment]
@XenthisX Hey sorry it's been quite on this end. We'll be pushing a pretty big update out here soon and then the focus is going to start to shift towards breaking out the game engine so I'll be in touch soon about this. Thanks again for coming out!

**Comment by oconn** [comment]
@elibosley The big refactor is in and I thought i'd let you know this work will be ramping up very soon. Hit me up if you're still interested in helping out with it.

**Comment by elibosley** [comment]
@oconn I definitely am. Let me know how I can help out and I'll see if what I can do.

**Comment by oconn** [comment]
Associated with #104

**Comment by morganedmonds** [comment]
Not adding additional language support for V1, closing.
