### ISSUE TITLE
Website Won't Open

### ISSUE THREAD

**Issue by generation359** [willowtreeapps/wombats-api#92]
The link posted in the wiki for the website (http://battlebots.willowtreemobile.com/) won't open. It opens the chrome error page with the text 

battlebots.willowtreemobile.com’s server DNS address could not be found.

**Comment by oconn** [comment]
Thanks for reporting this. We're going through a bit of rebranding right now (battlebots -> wombats) and a bit of the documentation needs to be updated. Updating all the documentation is on my shortlist right now. As for the public server, we will be making some significant changes here soon so I will get a new link posted as soon as I can. For the time being the cli display is your best bet for visualizing the arena and testing a bot.

**Comment by oconn** [comment]
Moving this issue to https://github.com/willowtreeapps/wombats-web-client/issues/9.
